apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-security-example
  labels:
    app: spring-security-example
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: spring-security-example
  template:
    metadata:
      labels:
        app: spring-security-example
    spec:
      containers:
        - name: spring-security-example
          image: spring-security-example:1.0   # 로컬에서 빌드한 이미지 이름
          imagePullPolicy: Never               # Docker Hub에서 가져오지 않도록 설정
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default

