apiVersion: v1
kind: Service
metadata:
  name: spring-security-service
spec:
  type: NodePort
  selector:
    app: spring-security-example
  ports:
    - protocol: TCP
      port: 8088          # 서비스 내부 포트
      targetPort: 8088    # 컨테이너 포트
      nodePort: 30088     # 외부 접근 포트 (localhost:30088)

