apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-security-example
  labels:
    app: spring-security-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-security-example
  template:
    metadata:
      labels:
        app: spring-security-example
    spec:
      containers:
        - name: spring-security-example
          image: spring-security-example:1.0   # 로컬 이미지
          imagePullPolicy: Never                # Minikube 로컬 이미지 사용
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default

---
apiVersion: v1
kind: Service
metadata:
  name: spring-security-service
spec:
  type: NodePort
  selector:
    app: spring-security-example
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30088
